### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by aallan** [leswright1977/RPI4_NCS2#1]
After replacing the `setupvars.sh` script I'm getting the following import error on running code,

```
Traceback (most recent call last):
  File "./benchmark_intel.py", line 3, in <module>
    from armv7l.openvino.inference_engine import IENetwork, IEPlugin
  File "/home/pi/openvino/inference_engine_vpu_arm/python/python3.5/armv7l/openvino/inference_engine/__init__.py", line 1, in <module>
    from .ie_api import *
ImportError: libinference_engine.so: cannot open shared object file: No such file or directory
```
looks like a copy of `libinference_engine.so` is located in the following places,

```
openvino/inference_engine_vpu_arm/deployment_tools/inference_engine/lib/armv7l/libinference_engine.so
openvino/inference_engine_vpu_arm/inference_engine/lib/armv7l/libinference_engine.so
```
any thoughts?

**Comment by leswright1977** [comment]
Hmm, looks like /home/pi/openvino/inference_engine_vpu_arm/python/python3.5/armv7l/openvino/inference_engine/__init__.py is not finding the shared libs

Manually check your environment variables, first

Also check this file exists : :/home/pi/openvino/inference_engine_vpu_arm//python/python3.5/libpython3.5m.so.1.0

**Comment by r91andersson** [comment]
How did you solve this @aallan ?
I got the exact same problem. I followed your guide here: https://www.hackster.io/news/getting-started-with-the-intel-neural-compute-stick-2-and-the-raspberry-pi-6904ccfe963
Thanks!

**Comment by r91andersson** [comment]
I just found a solution, by exporting the corresponding path to the libinference: expor tLD_LIBRARY_PATH=/home/pi/inference_engine_vpu_arm/inference_engine/lib/armv7l
